### ISSUE TITLE
npm installation of v3.13.0 fails

### ISSUE THREAD

**Issue by mpfeil** [pulumi/pulumi-openstack#340] opened 2023-08-07 12:31 UTC
### What happened?

I am trying to run `pulumi new openstack-typescript` to set up new basic project to test pulumi. Running the command fails installing the dependencies with the following error:
```
Installing dependencies...

npm ERR! code 1
npm ERR! path FOLDER_REDACTED/pulumi/quickstart/node_modules/@pulumi/openstack
npm ERR! command failed
npm ERR! command sh -c node scripts/install-pulumi-plugin.js resource openstack v3.13.0
npm ERR! node:internal/modules/cjs/loader:1051
npm ERR!   throw err;
npm ERR!   ^
npm ERR!
npm ERR! Error: Cannot find module 'FOLDER_REDACTED/pulumi/quickstart/node_modules/@pulumi/openstack/scripts/install-pulumi-plugin.js'
npm ERR!     at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
npm ERR!     at Module._load (node:internal/modules/cjs/loader:901:27)
npm ERR!     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
npm ERR!     at node:internal/main/run_main_module:23:47 {
npm ERR!   code: 'MODULE_NOT_FOUND',
npm ERR!   requireStack: []
npm ERR! }
npm ERR!
npm ERR! Node.js v20.5.0
```

Was trying to run it with different node versions but it always failed.

Just got it working setting up a project an installing v3.12.1 manually.

### Expected Behavior

`pulumi new openstack-typescript` runs without an error.

### Steps to reproduce

Running `pulumi new openstack-typescript` should be the only step to reproduce.

### Output of `pulumi about`

```
CLI
Version      3.77.1
Go Version   go1.20.6
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown

Host
OS       darwin
Version  13.4.1
Arch     arm64

This project is written in nodejs: executable='/usr/local/bin/node' version='v20.5.0'
```

### Additional context

Installing `v3.12.1` is no problem.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment] 2023-08-08 14:38
Hi @mpfeil. Thanks for letting us know about this. I can confirm that `pulumi new openstack-typescript` fails.

--- 

It looks like we didn't publish the `scripts` directory used during the install: https://www.npmjs.com/package/@pulumi/openstack?activeTab=code. The directory is present in repo: https://github.com/pulumi/pulumi-openstack/tree/v3.13.0/sdk/nodejs/scripts. The install failed because it tried to call a script from the `scripts` repo.

**Comment by Frassle** [comment] 2023-08-10 07:12
Wonder if this is https://github.com/pulumi/pulumi/issues/13195 again?

**Comment by iwahbe** [comment] 2023-08-10 08:29
If so, then https://github.com/pulumi/pulumi/issues/13195 is a P1. Is there a way to verify?

**Comment by aq17** [comment] 2023-08-11 22:50
Hi @mpfeil , this issue should be fixed now. Please reopen the issue and let us know if you encounter any additional problems!

**Closed by aq17** 2023-08-11 22:50 UTC
Labels: resolution/fixed, p1, kind/bug
